name: fast_dart_api
description: A starting point for pythons FastApi port in dart.
version: 0.0.1
repository: https://github.com/harsimran-d/fast_dart_api.git

environment:
  sdk: ^3.5.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
